/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef spiderDownloadInfo_CONSTANTS_H
#define spiderDownloadInfo_CONSTANTS_H

#include "spiderDownloadInfo_types.h"



class spiderDownloadInfoConstants {
 public:
  spiderDownloadInfoConstants();

};

extern const spiderDownloadInfoConstants g_spiderDownloadInfo_constants;



#endif
